version: '3'
services:
  todo:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/todo_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: secret_demo
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret_demo
      MYSQL_DATABASE: todo_db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
